---- Catalog seed
-- Safe to re-run. Existing rows are preserved.

INSERT INTO public.benchmarks (id, category, display_name, unit, higher_is_better) VALUES
  ('cpu.clock_gettime_libc',        'cpu',       'clock_gettime (CLOCK_MONOTONIC)',          'ns_per_op',   false),
  ('cpu.getpid_libc',               'cpu',       'getpid()',                                 'ns_per_op',   false),
  ('cpu.sched_yield_libc',          'cpu',       'sched_yield()',                            'ns_per_op',   false),
  ('cpu.thread_create_libc',        'cpu',       'pthread_create + join',                    'us_per_op',   false),
  ('cpu.context_switch_libc',       'cpu',       'Context switch round-trip (pipe)',         'us_per_op',   false),
  ('memory.mmap_anon_fault',        'memory',    'mmap+fault (anonymous)',                   'us_per_op',   false),
  ('memory.mmap_cycle',             'memory',    'mmap+munmap round-trip',                   'us_per_op',   false),
  ('memory.memcpy_bandwidth',       'memory',    'memcpy() bandwidth',                       'gb_per_sec',  true),
  ('memory.stride_sweep',           'memory',    'Stride-sweep (cache latency)',             'ns_per_op',   false),
  ('memory.malloc_free',            'memory',    'malloc()+free() latency',                  'ns_per_op',   false),
  ('memory.file_backed_mmap',       'memory',    'File-backed mmap R/W',                     'gb_per_sec',  true),
  ('scheduler.mutex_pingpong',      'scheduler', 'Mutex ping-pong (2 threads)',              'ns_per_op',   false),
  ('scheduler.barrier_latency',     'scheduler', 'pthread_barrier latency (4 threads)',      'us_per_op',   false),
  ('scheduler.rwlock_contention',   'scheduler', 'pthread_rwlock read-contention (8 readers)', 'ns_per_op', false),
  ('scheduler.yield_storm',         'scheduler', 'sched_yield storm (8 threads)',            'ops_per_sec', true),
  ('scheduler.message_flood',       'scheduler', 'MPSC message flood (4 senders)',           'ops_per_sec', true),
  ('ipc.pipe_throughput',           'ipc',       'Pipe throughput',                          'mb_per_sec',  true),
  ('ipc.pipe_latency',              'ipc',       'Pipe round-trip latency',                  'us_per_op',   false),
  ('ipc.unix_socket_stream',        'ipc',       'Unix socket stream throughput',            'mb_per_sec',  true),
  ('ipc.unix_socket_dgram',         'ipc',       'Unix socket datagram PPS',                 'ops_per_sec', true),
  ('ipc.epoll_wakeup_latency',      'ipc',       'epoll_wait wakeup latency',                'ns_per_op',   false),
  ('ipc.epoll_scalability',         'ipc',       'epoll scalability (100 fds)',              'us_per_op',   false),
  ('io.seq_write',                  'io',        'Sequential write throughput',              'mb_per_sec',  true),
  ('io.seq_read',                   'io',        'Sequential read throughput',               'mb_per_sec',  true),
  ('io.rand_write',                 'io',        'Random write (4KB blocks)',                'us_per_op',   false),
  ('io.rand_read',                  'io',        'Random read (4KB blocks)',                 'us_per_op',   false),
  ('io.mmap_file_rw',               'io',        'mmap file sequential R/W',                 'mb_per_sec',  true),
  ('io.metadata_ops',               'io',        'Metadata ops (open/fstat/close)',          'us_per_op',   false),
  ('network.tcp_throughput',        'network',   'TCP loopback throughput',                  'mb_per_sec',  true),
  ('network.tcp_latency',           'network',   'TCP loopback round-trip latency',          'us_per_op',   false),
  ('network.udp_pps',               'network',   'UDP loopback packets-per-second',          'ops_per_sec', true),
  ('network.epoll_server',          'network',   'epoll server scalability (50 clients)',    'ops_per_sec', true),
  ('timer.nanosleep_jitter',        'timer',     'nanosleep(1ms) jitter',                    'us_per_op',   false),
  ('timer.nanosleep_accuracy_1us',  'timer',     'nanosleep(1us) accuracy',                  'us_per_op',   false),
  ('timer.clock_resolution',        'timer',     'CLOCK_MONOTONIC resolution',               'ns_per_op',   false)
ON CONFLICT (id) DO NOTHING;
