name: Build Libs

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout    
        uses: actions/checkout@v4

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Compile
        run: |
          ndk-build NDK_PROJECT_PATH="." APP_BUILD_SCRIPT="Android.mk" NDK_APPLICATION_MK="Application.mk"
                           
      - name: Upload libs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: libs